import type { Metadata } from "next";
import { Andada_Pro, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { AppContextProvider } from "@/context/AppContext";

const andada = Andada_Pro({
  variable: "--font-andada",
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${andada.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${andada.className} min-h-full flex flex-col`}>
        <AppContextProvider>
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3500,
              style: {
                borderRadius: "16px",
                background: "#03081f",
                color: "#fff",
              },
              success: {
                style: {
                  background: "#03081f",
                },
              },
            }}
          />

          {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
