import type { Metadata } from "next";
import { Andada_Pro, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const andada = Andada_Pro({
  variable: "--font-andada",
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${andada.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${andada.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
